# Generated by Django 4.1.5 on 2023-01-27 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_directoryversion_options_directoryelement'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefbookElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, verbose_name='Код')),
                ('value', models.CharField(max_length=300, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Элемент справочника',
                'verbose_name_plural': 'Элементы справочников',
                'ordering': ['refbook_version__refbook__name', 'refbook_version__version', 'value'],
            },
        ),
        migrations.CreateModel(
            name='RefbookVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50, verbose_name='Версия')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала действия')),
            ],
            options={
                'verbose_name': 'Версия справочника',
                'verbose_name_plural': 'Версии справочников',
                'ordering': ['refbook__name', 'version'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='directoryversion',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='directoryversion',
            name='directory',
        ),
        migrations.RenameModel(
            old_name='Directory',
            new_name='Refbook',
        ),
        migrations.DeleteModel(
            name='DirectoryElement',
        ),
        migrations.DeleteModel(
            name='DirectoryVersion',
        ),
        migrations.AddField(
            model_name='refbookversion',
            name='refbook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.refbook', verbose_name='Справочник'),
        ),
        migrations.AddField(
            model_name='refbookelement',
            name='refbook_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.refbookversion', verbose_name='Версия справочника'),
        ),
        migrations.AlterUniqueTogether(
            name='refbookversion',
            unique_together={('refbook', 'version'), ('refbook', 'start_date')},
        ),
        migrations.AlterUniqueTogether(
            name='refbookelement',
            unique_together={('refbook_version', 'code')},
        ),
    ]
