# Generated by Django 4.1.5 on 2023-01-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_refbookelement_refbookversion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refbookversion',
            name='start_date',
            field=models.DateField(verbose_name='Дата начала действия'),
        ),
    ]
