# Generated by Django 4.1.5 on 2023-01-31 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_refbookversion_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refbookelement',
            name='refbook_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.refbookversion', verbose_name='Версия справочника'),
        ),
        migrations.AlterField(
            model_name='refbookversion',
            name='refbook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.refbook', verbose_name='Справочник'),
        ),
    ]
